i need a reminder, like on a plaque or something: _being confused about simple code isn't your fault; coders are forced by needless & unintuitive constraints to twist our designs into strange & complex forms. with these tech, coding doesn't happen organically; it must be constantly refactored._ the two main, if not only, troublesome constraints are *scope* and *order*. these are especially present in purely functional style. looping with mutation still requires scoping, but does not suffer the problem in the below fp example. examples of things w/o order: prolog, relational databases (by their support of multiple indexes, and joins (using a table as an index for another table); basiaclly they implicitly identify relations by set-theoretic operations.)

ok, suppose that you've datum x and fns f & g. suppose that g effectively mutates x in a recursive loop. whether f takes x as a parameter depends on whether x is in f's scope. however, it cannot be in f's scope unless f is defined inside g's loop, which it isn't, because that would harm readability. truly this "should" be the case; if f & g both use x and x is mutated, then f must be somehow coordinated with g so that neither affects x in a way that the other was not expecting. a simple variety is that f only reads x while g both reads and mutates x, even with f & g executing in concurrent loops. here we see the basic trouble with pfp: _code's location affects the code itself_, viz parameterizing, either f → (f x) or (f x ...) → (f x ... y) &c, just to have data in scope. the cruft is in the binding clauses (including function parameters!) the trouble is in correctly nesting binding clauses, especially when loops whose bodies contain asymmetric control flow are involved.

if you don't know your data's relations, then you'll find yourself all too frequently changing:

. nesting of bind clauses
. function parameters
. return values, usually returning multiple values simultaneously so that they're passed to the next loop iteration, or are otherwise kept in some greater scope; whereas one may say `x=3`, if other vars `a`, `b`, `c`, `d`, & `e` are also in scope, then they must all be passed to the successive recursive loop invocation e.g. `if p then rec 3 a b c d e else rec x a b c d e`. much easier to just say `x=3 continue.` oh, yeah, that's a whole other thing that i forgot about: pfp doesn't support `break` & `continue` (generally `goto`), so it uses continuation-passing style to poorly yet effectively implement equivalent control flow. holy hell! :')

the welcome freedom of state is being able to mutate without regard to nesting of binding clauses or, more generally, scoping mechanisms. similar to binding clauses, we need not concern ourselves with which functions return values, and to where they return them. each return value is used in one of four possible ways:

. bound at top level
. passed as fn arg to another fn
. bound in scoped binding clause (e.g. `let` or `match`)
. unbound (return value discarded, unreachable, and usually thus automatically garbage collected)

*the annoyance with (p)fp is needing to properly re/arrange (especially when refactoring or still exploring the true structure of your code) scoped binding clauses as determined by to which fns that return values are eventually passed.* it is explicit, verbose, and thus generalizes poorly, is quite inflexible, and is a headache to maintain while refactoring. ironically, this is its very purpose: to be exact, explicit, and inflexible, so that it can be reasoned about unambiguously without possibility of the programmer failing to correctly trace through mutations or infer implicit facts about the program. naturally pfp is usually found with static, strongly-typed, compiled languages. with simplicity, sensible naming conventions, and tacit programming, mutation and can make for extremely elegant & maintainable code, as demonstrated by picolisp, which uses dynamic binding and lexical scoping with shadowing.

this is an issue of functions, regardless of whether a language supports lambdas (thus making it a _functional language_) or mutation. the best languages enable both lambdas and mutation, as these are both useful features: lambdas are a natural object in computing: they're computations! so of course they should be anonymous and first-class! mutation is an alternative form of computation; the only difference is the lifetime and anonymity of the computation's result. functions' results may be never named, only passed to another computation; mutation updates a specific binding's value; thus it affects dependent computations. it's good practice to write only pure functions; a function's result can always be bound to a variable. however! this variable may or may not be used for a _set of functions_. mutation may or may not be used often, and may be variably encapsulated. regardless, the inability to mutate forces the developer to use some apparent, crufty, unmaintainable, inelegant, limiting, utterly painful & demoralizing structures to compensate! i personally would never opt to use a system whose 2nd-fastest operation, after bitwise & elementary arithmetic, is mutation. the purity restriction is as ridiculous as a stack language that does not support named binds. sure coding may be fine enough, but it could always be better, and there are some occasions that are just programmer abuse.

.fp example

this example should be like when there _are_ side effects, e.g. a fn has a cond block and returns one datum in all cases except for one, in which case it does return one thing, but also...has a side effect? idk. it made sense for a second.

mutative version (picolisp):

[source,lisp]
----
(setq x 0 y 10 z ())
(while (< x 10)
  (if (even? y) (inc x)
      (do (setq y x)
          (cons! y z)
          (setq x (+ 2 x)))))
; updated x, y, & z are available for use
(map ((z) (/ (+ x z) y)) z)
----

purely functional style (racket scheme):

[source,scm]
----
; R returns (x y . z) which must be bound,
; then can be used only within the binding context.
(match (let R ([x 0] [y 10] [z '()])
         (cond [(even? y) (R (add1 x) y z)]
               [(null? z) (list x y)]
               [else (let ([y x]) (R x y `(,y . ,z)))]))
 [(list* x y z) (map (λ (z) (/ (+ x z) y)) z)])
----

TODO: alas, this example does not showcase the real trouble of needing to calculate the complex orientation of constrol flow and scope that can arise in pfp. i need for some things to be modified in one cond clause but not others.... i need, in the mutation version, for each cond clause, only a subset of vars be concerned. the less symmetric the relations, the better mutation is than pfp. this being said, mutation is always most elegant, so it's better said that pfp becomes worse as asymmetry increases; *functions cannot elegantly express asymmetric relations.*

functions' only context—their only relation to anything—is in their parameters and outputs. they cannot read from nor modify an environment; in other words, a function's context is whitelisted. this very obviously competes capability against verbosity; this is the very _feature_ of a function! functions are considered safe _because_ of their incapability or verbosity, that if something is not said explicitly (as a parameter) then it's known to not be modified. *functions are appropriate only when contextless or when asymmetry is low.*

pfp requires everything to be a function, and functions are the only ways to bring something into scope (`let` binds do not _bring_ anything into scope; they only bind functions of things already in scope to identifiers). thus you now need to arrange your control flow and binding statements such that 1. vars are in needed scopes; and 2. vars are taken as parameters and returned by functions that pass to other functions. a showcase variety of this problem is when vars happenstantially sharing common scope (e.g. both being in a loop) must be returned even though it's strange for the loop function to return those data together. however, they all _must_ be returned; else some would be unreachable! in summary, pfp requires that functions' parameters and return values are the only way to pass data among scopes, which can easily become horribly complex.

loops are recursive functions; named let's are practically alternative syntax for recursive lambdas, just as fixed points are. fp requires that all looping be recursion, vars passed to the loop/fn's successive iteration. when only some items are effectively mutated only when only some conditions are met, the purely functional encoding of that must be quite complex. fp is supposed to make code more readable, modular, and refactorable, and perhaps even easier to write. ironically fp is a set of constraints that makes code worse in all of those regards. the only possible advantage of fp is that it can make concurrent code easier. however, semaphores, stm, manual delimitation of mutation (like rust or clojure) or other common concurrency tools are usually far easier alternatives.
